Helal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portfolio/', include("portfolio.urls")),
    path('smart-tracker/', include("tracker.urls")),
    path('store/', include("store.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views


app_name = "portfolio"
urlpatterns = [
    path("about/", views.about, name="about"),
    path("skills/", views.skills, name="skills"),
    path("works/", views.works, name="works"),
    path("contact/", views.contact, name="contact"),
    path("fingers/", views.fingers, name="fingers"),
    path("downloader/", views.downloader, name="downloader"),
    path("rewriter/", views.rewriter, name="rewriter"),
]

store/urls.py
from django.urls import path
from . import views

app_name = "store"
urlpatterns = [
    path("", views.home, name="home"),
    path("products/", views.products, name="products"),
    path("product/<int:productID>/", views.product, name="product"),
    path("seller/<int:sellerID>/", views.seller, name="seller"),
    path("about/", views.about, name="about"),
    path("cart/", views.cart, name="cart"),
    path("testimonial/", views.testimonial, name="testimonial"),
    path("why/", views.why, name="why"),
    path("checkout/", views.checkout, name="checkout"),
    path("update_cart/", views.updateCart, name="update_cart"),
    path("new_order/", views.newOrder, name="new_order"),
    path("shipping_order/<int:shippingID>", views.shippingOrder, name="shipping_order"),
    path("orders/", views.orders, name="orders"),
    path("confirm_order/<int:shippingID>", views.confirmOrder, name="confirm_order"),
    path("register/", views.register, name="register"),
    path("register_check/<str:registration_type>/", views.register_check, name="register_check"),
    path("logout/", views.logout_, name="logout"),
]

tracker/urls.py
from django.urls import path
from . import views


app_name = "tracker"
urlpatterns = [
    path("main-page/", views.main_page, name="main-page"),
]

portfolio/models.py
from django.db import models

# Create your models here.

portfolio/views.py
from django.shortcuts import render

# Create your views here.


def about(request):
    return render(request, "portfolio/about.html")


def skills(request):
    return render(request, "portfolio/skills.html")


def works(request):
    return render(request, "portfolio/works.html")


def contact(request):
    return render(request, "portfolio/contact.html")


def fingers(request):
    return render(request, "portfolio/fingers.html")


def downloader(request):
    return render(request, "portfolio/downloader.html")


def rewriter(request):
    return render(request, "portfolio/rewriter.html")

portfolio/templates/portfolio/about.html
{% extends "portfolio/main.html" %}
{% load static %}
{% block title %}
    <title>Ahmed Helal | official site</title>
{% endblock %}
{% block content %}
    <div class="about content active hide" id="about">
        <div class="about-info">
            <div class="info">
                <div class="top">
                    <div class="headings">
                        <h2>Ahmed Hatem Helal</h2>
                        <h2>High school student at STEM Gharbiya</h2>
                        <h2>Part time freelancer</h2>
                    </div>
                    <img src="{% static "portfolio/images/logo.png" %}" alt="ahmed h. helal" />
                </div>
                <p>
                     Maybe not the best in that world, but what I
                    am sure from is that you will find what you are seeking on
                    here, with attractive designs, accurate details, high
                    performance, fast-working, and ready for any additions and
                    modifications at any time your job will be completed in the
                    specified time and better than expected.
                </p>
            </div>
        </div>
    </div>
{% endblock %}

portfolio/templates/portfolio/downloader.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="shortcut icon" href="{% static "portfolio/downloader/images/icon.ico" %}" type="image/x-icon" />
		<link rel="stylesheet" href="{% static "portfolio/downloader/downloader.css" %}" />
		<title>Video Downloader 1.2</title>
	</head>
	<body>
		<!-- Start Header -->
		<header class="header">
			<h4 class="about"><a href="{% url "portfolio:about" %}" target="_blank">About Developer</a></h4>
			<div class="header-content">
				<h1>
					Video Downloader <br />
					V 1.2 Desktop
				</h1>
				<p>
					&nbsp;&nbsp;&nbsp;A
					<span class="keyword">desktop application</span> for downloading
					<span class="keyword">youtube</span> videos with different qualities,
					in addition to download full
					<span class="keyword">youtube playlists</span> with button press.
				</p>
				<a href="{% static "portfolio/downloader/app/Video Downloader.rar" %}">
                    Download Now
                </a>
			</div>
		</header>
		<!-- End Header -->

		<!-- Start Features -->
		<div class="overview">
			<h2 class="title">Application Features</h2>
			<div class="features">
				<div class="feature animated show-from-left">
					<img src="{% static "portfolio/downloader/images/free.png" %}" alt="free product" />
					<h3>Free Product</h3>
					<span>It is available for everyone free without forign ads.</span>
				</div>
				<div class="feature animated show-from-bottom">
					<img src="{% static "portfolio/downloader/images/speed.png" %}" alt="speed downloading" />
					<h3>Unlimited Speed</h3>
					<span
						>Doesn't limit the download rate and uses the maximum available
						bandwidth.</span
					>
				</div>
				<div class="feature animated show-from-right">
					<img src="{% static "portfolio/downloader/images/easy.png" %}" alt="easy" />
					<h3>Easy To Use</h3>
					<span
						>Has a simple interface that makes that easy for users to use.</span
					>
				</div>
			</div>
			<div class="images">
				<img class="app" src="{% static "portfolio/downloader/images/api.png" %}" alt="api logo" />
				<div class="about">
					<div>
						-
						<span class="keyword"
							><a href="https://www.python.org/" target="_blank"
								>Python</a
							></span
						>
						is an interpreted high-level general-purpose programming language.
					</div>
					<div>
						-
						<span class="keyword"
							><a
								href="https://pytube.io/en/latest/api.html#youtube-object"
								target="_blank"
								>Pytube</a
							></span
						>
						Youtub API (Application program interface) library, is used as
						intermeiary between the Youtube videos or playlist and the
						application. It written in python.
					</div>
					<div>
						-
						<span class="keyword"
							><a href="https://www.youtube.com/" target="_blank"
								>Youtube</a
							></span
						>
						is an American online video sharing and social media platform owned
						by Google.
					</div>
				</div>
			</div>
		</div>
		<!-- End Features -->

		<!-- Start Screenshots -->
		<div class="screenshots">
			<h2>Application Screenshots</h2>
			<div>
				<img src="{% static "portfolio/downloader/images/app.png" %}" alt="app" class="animated show-from-left" />
				<p class="animated show-from-right">
					The main application interface, waiting for user input of the video
					link to start downloading.
				</p>
			</div>
			<div>
				<p class="animated show-from-left">
					Playlist section, is responsible for the youtube playlists. Public
					playlists only are supported in the app.
				</p>
				<img src="{% static "portfolio/downloader/images/app2.png" %}" alt="app2" class="animated show-from-right" />
			</div>
			<div>
				<img src="{% static "portfolio/downloader/images/download.png" %}" alt="download" class="animated show-from-left" />
				<p class="animated show-from-right">
					Downloading window showing both the statistics of downloading status
					and video details.
				</p>
			</div>
			<div>
				<p class="animated show-from-left">
					Playlist downloading window, specified for playlists downloading and
					shows both the progresses of playlist and current video downloading.
				</p>
				<img src="{% static "portfolio/downloader/images/download2.png" %}" alt="download2" class="animated show-from-right" />
			</div>
		</div>
		<!-- End Screenshots -->

		<!-- Start Footer -->
		<footer>
			<div class="info">
				<div class="app animated show-from-left">
					<h2>
						Video Downloader <br />
						V 1.2 Desktop
					</h2>
					<a href="{% static "portfolio/downloader/app/Video Downloader.rar" %}">
                        Download Now
                    </a>
				</div>
				<div class="contact animated show-from-right">
                    <a href="{% url "portfolio:about" %}" target="_blank">
    					<div class="portfolio">
                            <span>Ahmed Helal | official site</span>
                        </div>
                    </a>
                    <a href="{% url "portfolio:contact" %}" target="_blank">
                        <div class="outlook">
						    <span>ahmed.1919007@stemgharbiya.moe.edu.eg</span>
					    </div>
                    </a>
                    <a href="https://www.facebook.com/ahmedhatemezzathelal/" target="_blank">
                        <div class="facebook">
                            <span>Ahmed H. Helal</span>
                        </div>
                    </a>
                    <a href="{% url "portfolio:contact" %}" target="_blank">
                        <div class="gmail">
						    <span>ahmedhatemezzathelal@gmail.com</span>
					    </div>
                    </a>
                    <a href="{% url "portfolio:contact" %}" target="_blank">
                        <div class="whatsapp">
                            <span>+201003736146</span>
                        </div>
                    </a>
				</div>
			</div>
			<div class="copy">
				&copy;2021 All Rights Reserved By
				<span class="about">
					<strong><a href="{% url "portfolio:about" %}" target="_blank">Ahmed H. Helal</a></strong>
				</span>
			</div>
		</footer>
		<!-- End Footer -->
		<script src="{% static "portfolio/animation.js" %}"></script>
	</body>
</html>

portfolio/templates/portfolio/fingers.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="shortcut icon" href="{% static "portfolio/fingers/images/icon.ico" %}" type="image/x-icon" />
		<link rel="stylesheet" href="{% static "portfolio/fingers/fingers.css" %}" />
		<title>Fingers Shortcut 1.0</title>
	</head>
	<body>
		<!-- Start Header -->
		<header class="header">
			<h4 class="about"><a href="{% url "portfolio:about" %}" target="_blank">About Developer</a></h4>
			<div class="header-content">
				<h1>
					Fingers Shortcuts <br />
					V 1.0 Desktop
				</h1>
				<p>
					&nbsp;&nbsp;&nbsp;A
					<span class="keyword">computer vision</span> application with
					implementation of <span class="keyword">AI smart hand detection</span>,
					which allows users to create specific operation and assign them to
					fingers pattern, performing those tasks when
					<span class="keyword">camera</span> detects the specified
					<span class="keyword">fingers pattern</span>.
				</p>
                <a href="{% static "portfolio/fingers/app/Fingers Shortcuts 1.0.rar" %}">
                    Download Now
                </a>
			</div>
		</header>
		<!-- End Header -->

		<!-- Start Features -->
		<div class="overview">
			<h2 class="title">Application Features</h2>
			<div class="features">
				<div class="feature animated show-from-left">
					<img src="{% static "portfolio/fingers/images/ai.png" %}" alt="smart detection" />
					<h3>Smart Detection</h3>
					<span>Can detect hand landmarks wherever the hand position.</span>
				</div>
				<div class="feature animated show-from-bottom">
					<img src="{% static "portfolio/fingers/images/performance.png" %}" alt="fast performance" />
					<h3>Fast Performance</h3>
					<span>Performing shortcuts fast once they have detected.</span>
				</div>
				<div class="feature animated show-from-right">
					<img src="{% static "portfolio/fingers/images/options.png" %}" alt="options" />
					<h3>Multiple Options</h3>
					<span>Provides lots of user options and specifications.</span>
				</div>
			</div>
			<div class="images">
				<img class="app" src="{% static "portfolio/fingers/images/libs.png" %}" alt="app screen" />
				<div class="about">
					<div>
						-
						<span class="keyword"
							><a href="https://opencv.org/" target="_blank">OpenCV</a></span
						>
						(Open Source Computer Vision) is an open source computer vision and
						machine learning software library.
					</div>
					<div>
						-
						<span class="keyword"
							><a href="https://www.python.org/" target="_blank"
								>Python</a
							></span
						>
						is an interpreted high-level general-purpose programming language.
					</div>
					<div>
						-
						<span class="keyword"
							><a href="https://numpy.org/" target="_blank">NumPy</a></span
						>
						is an open source project aiming to enable numerical computing with
						Python.
					</div>
				</div>
			</div>
		</div>
		<!-- End Features -->

		<!-- Start Screenshots -->
		<div class="screenshots">
			<h2>Application Screenshots</h2>
			<div class="app">
				<img src="{% static "portfolio/fingers/images/app.png" %}" alt="app" class="animated show-from-left" />
				<p class="animated show-from-right">
					Application main window, contains list of user option including camera
					options used in webcam connection and its port number, in addition to
					visualization options allowing users to define the visual screen size,
					view statistics, and color of visual screen text, etc.
				</p>
			</div>
			<div class="shortcuts">
				<p class="animated show-from-left">
					Shortcuts tab, responsible for shortcuts management: adding, editing,
					deleteing or clear the whole data.
					<br />
					Shortcuts can be either opening file\s or pressing keyboard keys
					sequence or performing specific command using CMD.
				</p>
				<img src="{% static "portfolio/fingers/images/shortcuts.png" %}" alt="shortcuts" class="animated show-from-right" />
			</div>
			<div class="visual">
				<img src="{% static "portfolio/fingers/images/visual.png" %}" alt="visual" class="animated show-from-left" />
				<p class="animated show-from-right">
					Visual window, appears when visual option (in display tab) is checked
					showing the hands landmarks detection and the pattern of raised
					fingers.
				</p>
			</div>
		</div>
		<!-- End Screenshots -->

		<!-- Start Footer -->
		<footer>
			<div class="info">
				<div class="app animated show-from-left">
					<h2>
						Fingers Shortcuts <br />
						V 1.0 Desktop
					</h2>
                    <a href="{% static "portfolio/fingers/app/Fingers Shortcuts 1.0.rar" %}">
                        Download Now
                    </a>
				</div>
				<div class="contact animated show-from-right">
                    <a href="{% url "portfolio:about" %}" target="_blank">
    					<div class="portfolio">
                            <span>Ahmed Helal | official site</span>
                        </div>
                    </a>
                    <a href="{% url "portfolio:contact" %}" target="_blank">
                        <div class="outlook">
						    <span>ahmed.1919007@stemgharbiya.moe.edu.eg</span>
					    </div>
                    </a>
                    <a href="https://www.facebook.com/ahmedhatemezzathelal/" target="_blank">
                        <div class="facebook">
                            <span>Ahmed H. Helal</span>
                        </div>
                    </a>
                    <a href="{% url "portfolio:contact" %}" target="_blank">
                        <div class="gmail">
						    <span>ahmedhatemezzathelal@gmail.com</span>
					    </div>
                    </a>
                    <a href="{% url "portfolio:contact" %}" target="_blank">
                        <div class="whatsapp">
                            <span>+201003736146</span>
                        </div>
                    </a>
				</div>
			</div>
			<div class="copy">
				&copy;2021 All Rights Reserved By
				<span class="about">
					<strong><a href="{% url "portfolio:about" %}" target="_blank">Ahmed H. Helal</a></strong>
				</span>
			</div>
		</footer>
		<!-- End Footer -->
		<script src="{% static "portfolio/animation.js" %}"></script>
	</body>
</html>

portfolio/templates/portfolio/main.html
{% load static %}
{% url "portfolio:about" as about %}
{% url "portfolio:skills" as skills %}
{% url "portfolio:works" as works %}
{% url "portfolio:contact" as contact %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="shortcut icon" type="image/png" href="{% static 'portfolio/images/favicon.png' %}"/>
		<link rel="stylesheet" href="{% static "portfolio/portfolio.css" %}" />
        {% block title %}
            <title>Ahmed Helal</title>
        {% endblock %}
	</head>
	<body>
        <div class="load" id="load">
            <div class="letter">L</div>
            <div class="letter">O</div>
            <div class="letter">A</div>
            <div class="letter">D</div>
            <div class="letter">I</div>
            <div class="letter">N</div>
            <div class="letter">G</div>
            <div class="letter">.</div>
            <div class="letter">.</div>
            <div class="letter">.</div>
        </div>
		<main>
            <div id="background-wrap">
                <div class="bubble x1"></div>
                <div class="bubble x2"></div>
                <div class="bubble x3"></div>
                <div class="bubble x4"></div>
                <div class="bubble x5"></div>
                <div class="bubble x6"></div>
                <div class="bubble x7"></div>
                <div class="bubble x8"></div>
                <div class="bubble x9"></div>
                <div class="bubble x10"></div>
                <div class="bubble x11"></div>
                <div class="bubble x12"></div>
                <div class="bubble x13"></div>
                <div class="bubble x14"></div>
                <div class="bubble x15"></div>
                <div class="bubble x16"></div>
                <div class="bubble x17"></div>
                <div class="bubble x18"></div>
                <div class="bubble x19"></div>
                <div class="bubble x20"></div>
            </div>
			<div class="glass hide" id="glass">
				<nav class="dashboard hide" id="dashboard">
					<div class="person">
						<img src="{% static "portfolio/images/avatar.jpg" %}" alt="Ahmed H. Helal" />
						<h3>Ahmed H. Helal</h3>
						<p>Full Stack Developer</p>
					</div>
					<button class="navbar-toggler" id="toggler">
						<span></span>
					</button>
					<div class="links" id="links">
                        <a href="{{ about }}">
                            <div class="link {% if request.path == about %} selected {% endif %}" data-content="about">
                                <img src="{% static "portfolio/images/about.png" %}" alt="about" />
                                <h3>About</h3>
                            </div>
                        </a>
                        <a href="{{ works }}">
                            <div class="link {% if request.path == works %} selected {% endif %}" data-content="works">
                                <img src="{% static "portfolio/images/portfolio.png" %}" alt="portfolio" />
                                <h3>Works</h3>
                            </div>
                        </a>
                        <a href="{{ skills }}">
                            <div class="link {% if request.path == skills %} selected {% endif %}" data-content="skills">
                                <img src="{% static "portfolio/images/skills.png" %}" alt="skills" />
                                <h3>Skills</h3>
                            </div>
                        </a>
                        <a href="{{ contact }}">
                            <div class="link {% if request.path == contact %} selected {% endif %}" data-content="contact">
                                <img src="{% static "portfolio/images/contact.png" %}" alt="contact" />
                                <h3>Contact</h3>
                            </div>
                        </a>
					</div>
				</nav>
				{% block content %}

				{% endblock %}
			</div>
		</main>
		<script src="{% static "portfolio/portfolio.js" %}"></script>
	</body>
</html>

portfolio/templates/portfolio/rewriter.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="shortcut icon" href="{% static "portfolio/rewriter/images/icon.ico" %}" type="image/x-icon" />
		<link rel="stylesheet" href="{% static "portfolio/rewriter/rewriter.css" %}" />
		<title>Correct Rewriter 0.3</title>
	</head>
	<body>
		<!-- Start Header -->
		<header class="header">
			<h4 class="about"><a href="{% url "portfolio:about" %}" target="_blank">About Developer</a></h4>
			<div class="header-content">
				<h1>
					Correct Rewriter <br />
					V 0.3 Desktop & Chrome Extension
				</h1>
				<p>
					&nbsp;&nbsp;&nbsp;A
					<span class="keyword">Desktop & chrome extension</span> automated
					application, is good for people who deal with
					<span class="keyword">arabic</span> and
					<span class="keyword">english</span> languages, can
					<span class="keyword">convert</span> the
					<span class="keyword">wrong written</span> words with one language to
					another on the fly.
				</p>
                <a href="{% static "portfolio/rewriter/app/Correct Rewriter 0.3.rar" %}">
                    Download Now
                </a>
			</div>
		</header>
		<!-- End Header -->

		<!-- Start Features -->
		<div class="overview">
			<h2 class="title">Application Features</h2>
			<div class="features">
				<div class="feature animated show-from-left">
					<img src="{% static "portfolio/rewriter/images/automated.png" %}" alt="automated mechanism" />
					<h3>Automation Handling</h3>
					<span
						>Just click the app icon and the text will be corrected and copied
						to clipboard automatically.</span
					>
				</div>
				<div class="feature animated show-from-bottom">
					<img src="{% static "portfolio/rewriter/images/async.png" %}" alt="async workspace" />
					<h3>Async Workspace</h3>
					<span
						>Can work as background task (a tray icon in taskbar) without
						interrupting the main operations.
                    </span>
				</div>
				<div class="feature animated show-from-right">
					<img src="{% static "portfolio/rewriter/images/chrome.png" %}" alt="chrome extension" />
					<h3>Chrome Extension</h3>
					<span>available to use in the chrome as extension.</span>
				</div>
			</div>
			<div class="images">
				<img class="app" src="{% static "portfolio/rewriter/images/automation.png" %}" alt="automation" />
				<div class="about">
					<div>
						-
						<span class="keyword"
							><a href="https://www.python.org/" target="_blank"
								>Python</a
							></span
						>
						is an interpreted high-level general-purpose programming language.
					</div>
					<div>
						-
						<span class="keyword"
							><a href="https://www.w3schools.com/whatis/" target="_blank"
								>Web Features</a
							></span
						>
						multiple languages such HTML, CSS, and JS. Are used in the chrome
						extension page.
					</div>
					<div>
						-
						<span class="keyword"
							><a href="https://doc.qt.io/qtforpython/" target="_blank"
								>PyQt5</a
							></span
						>
						is a python binding of the cross-platform GUI toolkit Qt,
						implemented as a Python plug-in. It is free software developed by
						the British firm Riverbank Computing.
					</div>
				</div>
			</div>
		</div>
		<!-- End Features -->

		<!-- Start Screenshots -->
		<div class="screenshots">
			<h2>Application Screenshots</h2>
			<div class="app">
				<img src="{% static "portfolio/rewriter/images/app.png" %}" alt="app" class="animated show-from-left" />
				<p class="animated show-from-right">
					Application main window, once opened it accesses the clipboard and get
					the copied text, then correcting it and copy the correct one to
					clipboard again.
				</p>
			</div>
			<div class="shortcuts">
				<p class="animated show-from-left">
					Popup screen attached to chrome extension, can perform the application
					main algorithm on the text within chrome.
				</p>
				<img src="{% static "portfolio/rewriter/images/popup.png" %}" alt="popup" class="animated show-from-right" />
			</div>
			<div>
				<img
					src="{% static "portfolio/rewriter/images/extension.png" %}"
					alt="extension"
					class="animated show-from-left"
				/>
				<p class="animated show-from-right">
					The extension script modifying the html pages by adding a small icon at
					the end of each text box in the page, and correcting the texts on the
					fly.
				</p>
			</div>
		</div>
		<!-- End Screenshots -->

		<!-- Start Footer -->
		<footer>
			<div class="info">
				<div class="app animated show-from-left">
					<h2>
						Correct Rewriter <br />
						V 0.3 Desktop & Chrome Extension
					</h2>
                    <a href="{% static "portfolio/rewriter/app/Correct Rewriter 0.3.rar" %}">
                        Download Now
                    </a>
				</div>
				<div class="contact animated show-from-right">
                    <a href="{% url "portfolio:about" %}" target="_blank">
    					<div class="portfolio">
                            <span>Ahmed Helal | official site</span>
                        </div>
                    </a>
                    <a href="{% url "portfolio:contact" %}" target="_blank">
                        <div class="outlook">
						    <span>ahmed.1919007@stemgharbiya.moe.edu.eg</span>
					    </div>
                    </a>
                    <a href="https://www.facebook.com/ahmedhatemezzathelal/" target="_blank">
                        <div class="facebook">
                            <span>Ahmed H. Helal</span>
                        </div>
                    </a>
                    <a href="{% url "portfolio:contact" %}" target="_blank">
                        <div class="gmail">
						    <span>ahmedhatemezzathelal@gmail.com</span>
					    </div>
                    </a>
                    <a href="{% url "portfolio:contact" %}" target="_blank">
                        <div class="whatsapp">
                            <span>+201003736146</span>
                        </div>
                    </a>
				</div>
			</div>
			<div class="copy">
				&copy;2021 All Rights Reserved By
				<span class="about">
					<strong><a href="{% url "portfolio:about" %}">Ahmed H. Helal</a></strong>
				</span>
			</div>
		</footer>
		<!-- End Footer -->
		<script src="{% static "portfolio/animation.js" %}"></script>
	</body>
</html>

portfolio/templates/portfolio/works.html
{% extends "portfolio/main.html" %}
{% load static %}
{% block title %}
    <title>Ahmed Helal | works</title>
{% endblock %}
{% block content %}
    <div class="works content active hide" id="works">
        <div class="works-info">

            <div class="fingers-shortcut">
                <h2>Fingers Shortcuts 1.0</h2>
                <img src="{% static "portfolio/fingers/images/logo.png" %}" alt="fingers shortcuts" />
                <p>
                    AI Desktop application use to assign specific windows task with fingers pattern, and using
                    camera to detect the hand landmarks pattern to perform the task related to it, and can run
                    as a background application.
                </p>
                <a href="{% url "portfolio:fingers" %}" target="_blank">
                    <button>
                        <span>Visit Site</span>
                    </button>
                </a>
            </div>

            <div class="separator"></div>

            <div class="smart-tracker">
                <h2>Smart Tracker</h2>
                <img src="{% static "tracker/images/logo.png" %}" alt="smart tracker" />
                <p>Interactive web page contains animated frontend layout of smart tracker application with HTML, CSS and JS.</p>
                <a href="{% url "tracker:main-page" %}" target="_blank">
                    <button>
                        <span>Visit Site</span>
                    </button>
                </a>
            </div>

            <div class="separator"></div>

            <div class="video-downloader">
                <h2>Video Downloader 1.2</h2>
                <img src="{% static "portfolio/downloader/images/logo.png" %}" alt="video downloader" />
                <p>Youtube video downloader written in python, can download youtube videos easily with different qualities without ads, and provides option to download full youtube playlists with one click.</p>
                <a href="{% url "portfolio:downloader" %}" target="_blank">
                    <button>
                        <span>Visit Site</span>
                    </button>
                </a>
            </div>

            <div class="separator"></div>

            <div class="online-shop">
                <h2>E-Commerce</h2>
                <img src="{% static "images/logo.png" %}" alt="online shop" />
                <p>Online Shop (E-Commerce) created with django - python and bootstrap, provides:</p>
                <ul>
                    <li>Easy-handle admin dashboard.</li>
                    <li>Users registration with cart feature for every user.</li>
                    <li>Full control on products and their sellers.</li>
                    <li>Organized system for users' orders.</li>
                    <li>Handling shipping information from users to deliverers and else.</li>
                </ul>
                <a href="{% url "store:register" %}" target="_blank">
                    <button>
                        <span>Visit Site</span>
                    </button>
                </a>
            </div>

            <div class="separator"></div>

            <div class="rewriter">
                <h2>Correct Rewriter 0.3</h2>
                <img src="{% static "portfolio/rewriter/images/logo.png" %}" alt="smart tracker" />
                <p>
                    Desktop application is used to convert the wrong written texts of keyboard different language
                    on the fly, provides chrome extension to run with chrome.
                    Supports Arabic and English only.
                </p>
                <a href="{% url "portfolio:rewriter" %}" target="_blank">
                    <button>
                        <span>Visit Site</span>
                    </button>
                </a>
            </div>

        </div>
    </div>
{% endblock %}