Helal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('portfolio/', include("portfolio.urls")),
    path('smart-tracker/', include("tracker.urls")),
    path('store/', include("store.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from . import views

app_name = "store"
urlpatterns = [
    path("", views.home, name="home"),
    path("products/", views.products, name="products"),
    path("product/<int:productID>/", views.product, name="product"),
    path("seller/<int:sellerID>/", views.seller, name="seller"),
    path("about/", views.about, name="about"),
    path("cart/", views.cart, name="cart"),
    path("testimonial/", views.testimonial, name="testimonial"),
    path("why/", views.why, name="why"),
    path("checkout/", views.checkout, name="checkout"),
    path("update_cart/", views.updateCart, name="update_cart"),
    path("new_order/", views.newOrder, name="new_order"),
    path("shipping_order/<int:shippingID>", views.shippingOrder, name="shipping_order"),
    path("orders/", views.orders, name="orders"),
    path("confirm_order/<int:shippingID>", views.confirmOrder, name="confirm_order"),
    path("register/", views.register, name="register"),
    path("register_check/<str:registration_type>/", views.register_check, name="register_check"),
    path("logout/", views.logout_, name="logout"),
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    phone = PhoneNumberField(null=True)
    city = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class DeliveryMan(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    phone = PhoneNumberField(null=True)

    class Meta:
        verbose_name = "Delivery Man"
        verbose_name_plural = "Delivery Men"

    def __str__(self):
        return self.name


class Seller(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    details = models.TextField(max_length=5000)
    phone = PhoneNumberField(null=True)
    img = models.ImageField(upload_to="store/images/products")

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.FloatField("Price")
    details = models.TextField()
    img = models.ImageField(upload_to="store/images/products", default="store/images/products/product.png")

    def __str__(self):
        return self.name


class Offer(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    start = models.DateTimeField("Date Start", auto_now_add=True)
    end = models.DateTimeField("Date End")

    def __str__(self):
        return "offer " + str(self.id)


class Cart(models.Model):
    user = models.ForeignKey(Customer, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)

    @property
    def total_quantity(self):
        total = sum([item.quantity for item in self.cartitem_set.all()])
        return total

    @property
    def total_price(self):
        total = sum([item.total_price for item in self.cartitem_set.all()])
        return total

    def __str__(self):
        return f"{self.user.name}'s cart"


class CartItem(models.Model):
    user = models.ForeignKey(Customer, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    date_added = models.DateTimeField("Date Added", auto_now_add=True)

    @property
    def total_price(self):
        total = self.product.price * self.quantity
        return total


class Shipping(models.Model):
    user = models.ForeignKey(Customer, on_delete=models.CASCADE)
    delivery_man = models.ForeignKey(DeliveryMan, on_delete=models.CASCADE, null=True)
    order = models.OneToOneField(Cart, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=200, default="")
    email = models.CharField(max_length=200, default="")
    address = models.CharField(max_length=200, default="")
    city = models.CharField(max_length=200, default="")
    phone = models.CharField(max_length=200, default="")
    date_ordered = models.DateTimeField("Date Ordered", auto_now_add=True)
    status = models.CharField(
        max_length=10,
        choices=[
            ("ordered", "Ordered"),
            ("confirmed", "Confirmed"),
            ("delivered", "Delivered"),
            ("canceled", "Canceled"),
            ],
        default="ordered"
    )

    def __str__(self):
        return f"order: {self.id}, {self.order}, {self.address}"

store/views.py
import json
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse

from .models import *
from django.shortcuts import get_object_or_404

# Create your views here.


def register(request):
    if request.user.is_authenticated:
        return redirect("store:home")
    else:
        return render(request, "store/register.html")


def register_check(request, registration_type):
    if not request.user.is_authenticated:
        if registration_type == "login":
            return loginValidation(request)
        else:
            return signupValidation(request)
    else:
        return redirect("store:home")


def loginValidation(request):
    username = request.POST.get("username")
    password = request.POST.get("password")
    login_error = None
    loginUsername = None
    try:
        login_error = "Username not found!"
        User.objects.get(username=username)
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return redirect("store:home")
        else:
            login_error = "Password is incorrect!"
            loginUsername = username
            raise Exception()

    except Exception as e:
        print(e)
        context = {
            "login_error": login_error,
            "login_username": loginUsername
        }
        return render(request, "store/register.html", context)


def signupValidation(request):
    firstName = request.POST.get("first name")
    lastName = request.POST.get("last name")
    username = request.POST.get("username")
    email = request.POST.get("email")
    address = request.POST.get("address")
    phone = request.POST.get("phone")
    city = request.POST.get("city")
    password = request.POST.get("password")
    confirmPassword = request.POST.get("confirm password")
    signup_error = None

    try:
        users = User.objects.filter(username=username)
        if len(users) > 0:
            signup_error = "Username not available!"
            raise Exception()
        if password != confirmPassword:
            signup_error = "Passwords aren't identical!"
            raise Exception()

        # create new user
        newUser = User.objects.create_user(
            username=username,
            email=email,
            password=password,
            first_name=firstName,
            last_name=lastName
        )
        # create new customer
        Customer.objects.create(
            user=newUser,
            name=f"{newUser.first_name.strip().title()} {newUser.last_name.strip().title()}",
            address=address,
            phone=phone,
            city=city
        )
        # log user in
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect("store:home")

    except Exception as e:
        print(e)
        context = {
            "signup": True,
            "signup_error": signup_error,
            "signup_first_name": firstName,
            "signup_last_name": lastName,
            "signup_email": email,
            "signup_address": address,
            "signup_phone": phone,
            "signup_city": city,
        }
        return render(request, "store/register.html", context)


def logout_(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect("store:register")


@login_required(login_url="/store/register/")
def home(request):
    items = Product.objects.all()
    offers = Offer.objects.all()
    context = {"items": items, "offers": offers}
    return render(request, "store/home.html", context)


def products(request):
    items = Product.objects.all()
    context = {"items": items}
    return render(request, "store/products.html", context)


def product(request, productID):
    item = get_object_or_404(Product, id=productID)
    context = {"item": item}
    return render(request, "store/product.html", context)


def seller(request, sellerID):
    shop = get_object_or_404(Seller, id=sellerID)
    context = {"seller": shop}
    return render(request, "store/seller.html", context)


def about(request):
    return render(request, "store/about.html")


@login_required(login_url="/store/register/")
def cart(request):
    user = request.user.customer
    try:
        newCart = Cart.objects.get(user=user, ordered=False)
    except Exception as e:
        print(e)
        newCart = None

    try:
        shipping_orders = Shipping.objects.filter(user=user)
    except Exception as e:
        print(e)
        shipping_orders = []
    context = {"newCart": newCart, "shipping_orders": shipping_orders}
    return render(request, "store/cart.html", context)


def testimonial(request):
    return render(request, "store/testimonial.html")


def why(request):
    return render(request, "store/why.html")


@login_required(login_url="/store/register/")
def checkout(request):
    order = Cart.objects.all().get(user=request.user.customer, ordered=False)
    context = {"usercart": order}
    return render(request, "store/checkout.html", context)


@login_required(login_url="/store/register/")
def orders(request):
    shipping = Shipping.objects.filter(status="ordered")
    confirmed_shipping = Shipping.objects.exclude(status="ordered")
    context = {"shipping": shipping, "confirmed_shipping": confirmed_shipping}
    return render(request, "store/shipping.html", context)


@login_required(login_url="/store/register/")
def shippingOrder(request, shippingID):
    shipping = Shipping.objects.get(id=shippingID)
    context = {"shipping": shipping}
    return render(request, "store/shipping_order.html", context)


@login_required(login_url="/store/register/")
def updateCart(request):
    user = request.user.customer
    order, created = Cart.objects.get_or_create(user=user, ordered=False)
    data = json.loads(request.body)
    productID = data["productID"]
    quantity = data["quantity"]
    action = data["action"]

    if action == "add-item":
        item, created = CartItem.objects.get_or_create(user=user, cart=order, product_id=productID)
        item.quantity = quantity
        item.save()
    elif action == "remove-item":
        item = CartItem.objects.get(user=user, cart=order, product_id=productID)
        item.delete()
        if order.cartitem_set.count() <= 0:
            order.delete()
    elif action == "remove-cart":
        order.delete()

    return HttpResponse("cart updated successfully")


@login_required(login_url="/store/register/")
def newOrder(request):
    user = request.user.customer
    order = Cart.objects.get(user=user, ordered=False)
    order.ordered = True
    order.save()

    data = request.POST
    name = data.get("name")
    email = data.get("email")
    address = data.get("address")
    city = data.get("city")
    phone = data.get("phone")
    shipping = Shipping(
        user=user,
        order=order,
        name=name,
        email=email,
        address=address,
        city=city,
        phone=phone
    )
    shipping.save()
    return cart(request)


@login_required(login_url="/store/register/")
def confirmOrder(request, shippingID):
    user = request.user.deliveryman
    shipping = Shipping.objects.get(id=shippingID)
    shipping.delivery_man = user
    shipping.status = "confirmed"
    shipping.save()
    return shippingOrder(request, shippingID)

store/templates/store/cart.html
{% extends 'store/main.html' %} {% load static %} {% block content %} {% url "store:home" as home %}
<div class="row pb-5">
	<div class="col-lg-12">

    {% if newCart %}

		<div class="box-element">
			<a class="btn btnn" href="{{ home }}">&#x2190; Continue Shopping</a>
			<br />
			<br />
			<table class="table">
				<tr>
					<th>
						<h5>Items: <strong>{{ newCart.total_quantity }}</strong></h5>
					</th>
					<th>
						<h5>
							Total:<strong> {{ newCart.total_price|floatformat:2 }} EGP</strong>
						</h5>
					</th>
					<th>
						<a style="float: right; margin: 5px" class="btn btnn" href="{% url "store:checkout" %}"
							>Order</a>
					</th>
				</tr>
			</table>
		</div>

		<br />

        <h3 style="color: #3a4468;text-align: center">New Items</h3>
		<div class="box-element">
			<div class="cart-row mt-5">
				<div style="flex: 1"></div>
				<div style="flex: 1"><strong>Item</strong></div>
				<div style="flex: 1"><strong>Price</strong></div>
				<div style="flex: 1"><strong>Quantity</strong></div>
				<div style="flex: 1"><strong>Total</strong></div>
                <div>
                    <span style="float: right; margin: 5px; background-color:#bd2130;" class="btn btnn" data-action="remove-cart" onclick="updateCart(this);">Remove Cart</span>
                </div>
			</div>

			{% for item in newCart.cartitem_set.all %}

			<div class="cart-row">
				<div style="flex: 1">
					<img class="row-image" src="/media/{{ item.product.img }}" />
				</div>
				<div style="flex: 1"><p><a href="{% url "store:product" item.product.id %}">{{ item.product.name }}</a></p></div>
				<div style="flex: 1">
					<p>{{ item.product.price|floatformat:2 }} EGP</p>
				</div>
				<div style="flex: 1">
					<p class="quantity">x {{ item.quantity }}</p>
					<div class="quantity">

					</div>
				</div>
				<div style="flex: 1"><p>{{ item.total_price|floatformat:2 }} EGP</p></div>
                <div><span style="float: right; margin: 5px; background-color:#bd2130;" class="btn btnn" data-id="{{ item.product.id }}" data-action="remove-item" onclick="updateCart(this);">Remove Item</span></div>
			</div>

			{% endfor %}


		</div>

    {% else %}

        <div class="box-element">
			<a class="btn btnn" href="{{ home }}">&#x2190; Continue Shopping</a>
			<br />
			<br />
			<h3 style="color: #dc3545 ;text-align: center">Your cart is empty.</h3>
		</div>

    {% endif %}

    {% if shipping_orders %}

        <h3 style="color: #3a4468;text-align: center" class="mt-5">Recent Orders</h3>
        <div class="box-element mt-5">
            <div class="cart-row">
                <div style="flex: 1"><strong>Date Ordered</strong></div>
                <div style="flex: 1"><strong>Address</strong></div>
                <div style="flex: 1"><strong>Price</strong></div>
                <div style="flex: 1"><strong>Quantity</strong></div>
                <div style="flex: 1"><strong>Status</strong></div>
                <div style="flex: 1"></div>
            </div>

        {% for shipping_order in shipping_orders %}
                    <div class="cart-row">
                        <div style="flex: 1"><strong>{{ shipping_order.date_ordered }}</strong></div>
                        <div style="flex: 1"><strong>{{ shipping_order.address }}</strong></div>
                        <div style="flex: 1"><strong>{{ shipping_order.order.total_price }} EGP</strong></div>
                        <div style="flex: 1"><strong>{{ shipping_order.order.total_quantity }}</strong></div>
                        <div style="flex: 1"><strong>
                            {% if shipping_order.status == "ordered" %}
                                <span style="color: #f3c93e;text-align: center">{{ shipping_order.status }}</span>
                            {% else %}
                                <span style="color: #28a745;text-align: center">{{ shipping_order.status }}</span>
                            {% endif %}</strong></div>
                        <div style="flex: 1"><a style="float: right; margin: 5px;" class="btn btnn" href="{% url "store:shipping_order" shipping_order.id %}">Details</a></div>
			</div>

        {% endfor %}

        </div>
    {% endif %}


	</div>
</div>
{% endblock %}

store/templates/store/footer.html
<!DOCTYPE html>
<html lang="en">
{% block links %}

{% endblock %}

<head>
    {% block head %}
        <meta charset="UTF-8">
        <title>Title</title>
    {% endblock %}
</head>
<body class="sub_page">
    {% block body %}

    {% endblock %}

    {% block footer %}

  <!-- info section -->
  <section class="info_section ">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="info_contact">
            <h5>
              <a href="" class="navbar-brand">
                <span>
                  Online Shop
                </span>
              </a>
            </h5>
            <p>
              <i class="fa fa-map-marker" aria-hidden="true"></i>
              Address
            </p>
            <p>
              <i class="fa fa-phone" aria-hidden="true"></i>
              +01 1234567890
            </p>
            <p>
              <i class="fa fa-envelope" aria-hidden="true"></i>
              demo@gmail.com
            </p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_info">
            <h5>
              Information
            </h5>
            <p>
              Eligendi sunt, provident, debitis nemo, facilis cupiditate velit libero dolorum aperiam enim nulla iste maxime corrupti ad illo libero minus.
            </p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_links">
            <h5>
              Useful Link
            </h5>
            <ul>
              <li>
                <a href="{% url "store:home" %}">
                  Home
                </a>
              </li>
              <li>
                <a href="{% url "store:about" %}">
                  About
                </a>
              </li>
              <li>
                <a href="{% url "store:products" %}">
                  Products
                </a>
              </li>
              <li>
                <a href="{% url "store:why" %}">
                  Why Us
                </a>
              </li>
              <li>
                <a href="{% url "store:testimonial" %}">
                  Testimonial
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_form ">
            <form action="">
              <input type="email" placeholder="Send Feedback">
              <button>
                Send
              </button>
            </form>
            <div class="social_box">
              <a href="">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-youtube" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end info_section -->


  <!-- footer section -->
  <footer class="footer_section">
    <div class="container">
      <p>
        &copy; <span id="displayYear"></span> All Rights Reserved By
        <a style="color: #f3c93e" href="{% url "store:about" %}">Ahmed Helal</a>
      </p>
    </div>
  </footer>
  <!-- footer section -->
    {% endblock %}
</body>
</html>

store/templates/store/main.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% url 'store:home' as home %}
{% url 'store:about' as about %}
{% url 'store:products' as products %}
{% url 'store:why' as why %}
{% url 'store:testimonial' as testimonial %}
{% url 'store:cart' as cart %}
{% url 'store:logout' as logout %}
<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <link rel="icon" href="{% static "images/favicon.png" %}" type="image/gif" />
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Asran Store - home page</title>


  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,700&display=swap" rel="stylesheet"> <!-- range slider -->

  <!-- font awesome style -->
  <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static "css/product.css" %}" rel="stylesheet" />
  <link href="{% static "css/style.css" %}" rel="stylesheet" />
  <link href="{% static "css/stylecart.css" %}" rel="stylesheet" />
  <link href="{% static "css/seller.css" %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static "css/responsive.css" %}" rel="stylesheet" />

</head>

<body class="sub_page">

  <div class="hero_area">
    <!-- header section starts -->
    <header class="header_section">
      <div class="header_top">
        <div class="container-fluid">
          <div class="top_nav_container">
            <div class="contact_nav">
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call : +01 123455678990
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  Email : demo@gmail.com
                </span>
              </a>
            </div>
            <from class="search_form">
              <input type="text" class="form-control" placeholder="Search here...">
              <button class="" type="submit">
                <i class="fa fa-search" aria-hidden="true"></i>
              </button>
            </from>
            <div class="user_option_box">
              <a href="" class="account-link">
                  {% if user.is_authenticated %}
                    <i class="fa fa-user" aria-hidden="true"></i>
                    <span>
                      {{ user.customer.name }}
                    </span>
                  {% endif %}
              </a>
              <a href="{{ cart }}" class="cart-link" {% if request.path == cart %}style="color: #f3c93e;" {% endif %}>
                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                <span>
                  Cart
                </span>
              </a>
              <a href="{{ logout }}" class="cart-link" >
                <img src="{% static "images/sign-out-alt-solid.svg" %}">
                <span>
                  Logout
                </span>
              </a>
            </div>
          </div>

        </div>
      </div>
      <div class="header_bottom">
        <div class="container-fluid">
          <nav class="navbar navbar-expand-lg custom_nav-container ">
            <a class="navbar-brand" href="{{ home }}">
              <span>
                Online Shop
              </span>
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class=""> </span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ">
                <li class="nav-item  {% if request.path == home %} active {% endif %}">
                  <a class="nav-link" href="{{ home }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item {% if request.path == about %} active {% endif %}">
                  <a class="nav-link" href="{{ about }}"> About</a>
                </li>
                <li class="nav-item {% if request.path == products %} active {% endif %}">
                  <a class="nav-link" href="{{ products }}">Products</a>
                </li>
                <li class="nav-item {% if request.path == why %} active {% endif %}">
                  <a class="nav-link" href="{{ why }}">Why Us</a>
                </li>
                <li class="nav-item {% if request.path == testimonial %} active {% endif %}">
                  <a class="nav-link"  href="{{ testimonial }}">Testimonial</a>
                </li>
              </ul>
            </div>
          </nav>
        </div>
      </div>
    </header>
    <!-- end header section -->
  {% block slider %}
  
  {% endblock %}
  </div>

  {% block content %}

  {% endblock %}


  <!-- info section -->
  <section class="info_section ">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="info_contact">
            <h5>
              <a href="" class="navbar-brand">
                <span>
                  Online Shop
                </span>
              </a>
            </h5>
            <p>
              <i class="fa fa-map-marker" aria-hidden="true"></i>
              Address
            </p>
            <p>
              <i class="fa fa-phone" aria-hidden="true"></i>
              +01 1234567890
            </p>
            <p>
              <i class="fa fa-envelope" aria-hidden="true"></i>
              demo@gmail.com
            </p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_info">
            <h5>
              Information
            </h5>
            <p>
              Eligendi sunt, provident, debitis nemo, facilis cupiditate velit libero dolorum aperiam enim nulla iste maxime corrupti ad illo libero minus.
            </p>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_links">
            <h5>
              Useful Link
            </h5>
            <ul>
              <li>
                <a href="{{ home }}">
                  Home
                </a>
              </li>
              <li>
                <a href="{{ about }}">
                  About
                </a>
              </li>
              <li>
                <a href="{{ products }}">
                  Products
                </a>
              </li>
              <li>
                <a href="{{ why }}">
                  Why Us
                </a>
              </li>
              <li>
                <a href="{{ testimonial }}">
                  Testimonial
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-3">
          <div class="info_form ">
            <form action="">
              <input type="email" placeholder="Send Feedback">
              <button>
                Send
              </button>
            </form>
            <div class="social_box">
              <a href="">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
              <a href="">
                <i class="fa fa-youtube" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end info_section -->

  <!-- footer section -->
  <footer class="footer_section">
    <div class="container">
      <p>
        &copy; <span id="displayYear"></span> All Rights Reserved By
        <a style="color: #f3c93e" href="{% url "store:about" %}">Ahmed Helal</a>
      </p>
    </div>
  </footer>
  <!-- footer section -->
  <!-- jQery -->
  <script src="{% static "js/jquery-3.4.1.min.js" %}"></script>
  <!-- bootstrap js -->
  <script src="{% static "js/bootstrap.js" %}"></script>
  <!-- custom js -->
  <script src="{% static "js/custom.js" %}"></script>
    <script>
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getCookie('csrftoken');
    </script>
    <script src="{% static "js/cart.js" %}"></script>
</body>

</html>

store/templates/store/product.html
{% extends "store/main.html" %} {% load static %} {% block content %}
<!-- product section -->

<section class="product_section layout_padding">
	<div class="container">
		<div class="heading_container heading_center">
			<h2>Product Details</h2>
		</div>
		<div class="row product-details">
			<div class="col-sm-12 col-lg-12">
				<div class="box">
					<div class="img-box">
						<img src="/media/{{ item.img }}" alt="">
					</div>
					<div class="detail-box">
						<h5>{{ item.name }}</h5>
						<div class="hr"></div>
						<div class="product_info">
							<div><span>Price:</span><span>{{ item.price }}EGP</span></div>
							<div><span>Category:</span><span>{{ item.category }}</span></div>
							<div><span>Seller:</span><span><a href="{% url "store:seller" item.seller.id %}"> {{ item.seller }} </a></span></div>
							<div class="hr"></div>
							<div class="details">
                                {{ item.details }}
							</div>

							<div class="hr"></div>
						</div>
						<div class="order_info">
							<div>
								<span>Quantity:</span>
								<span><input id="quantity" type="number" value="1" min="1" /></span>
							</div>
						</div>
						<div class="btn_box">
							<span class="view_more-link" data-id="{{ item.id }}" data-action="add-item" onclick="updateCart(this);"> Add To Cart </span>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<!-- end product section -->

{% endblock %}